# Generated by Django 5.1.7 on 2025-06-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permission',
            field=models.BooleanField(default=False),
        ),
    ]
