# Generated by Django 5.1.7 on 2025-08-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_profile_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='permission',
            field=models.BooleanField(default=False, verbose_name='Give Blog Permission'),
        ),
    ]
