# Generated by Django 5.1.7 on 2025-09-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_profile_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('ND1', 'ND1'), ('ND2', 'ND2'), ('HND1 NCC', 'HND1 NCC'), ('HND1 SWD', 'HND1 SWD'), ('HND2 NCC', 'HND2 NCC'), ('HND2 SWD', 'HND2 SWD')], max_length=20, null=True),
        ),
    ]
