# Generated by Django 5.1.7 on 2025-10-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_alter_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_class_rep',
            field=models.BooleanField(default=False, verbose_name='Class Rep?'),
        ),
    ]
