# Generated by Django 5.1.7 on 2025-04-14 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forum_save_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='save_count',
        ),
        migrations.AddField(
            model_name='forum',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='post_saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
