# Generated by Django 5.1.7 on 2025-04-14 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_forum_save_count_forum_saved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='repost',
            field=models.ManyToManyField(blank=True, related_name='repost', to=settings.AUTH_USER_MODEL),
        ),
    ]
