# Generated by Django 5.1.7 on 2025-05-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_notification_sender_notification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
