# Generated by Django 5.1.7 on 2025-09-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_forum_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaveItem',
        ),
    ]
