# Generated by Django 5.1.7 on 2025-09-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_delete_saveitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='saved',
        ),
    ]
