# Generated by Django 5.1.7 on 2025-10-23 06:28

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Campus', 'Campus'), ('Education', 'Education'), ('Social', 'Social'), ('Fellowship', 'Fellowship'), ('Research', 'Research')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Classes', verbose_name='Class Image')),
                ('timetable', models.ImageField(blank=True, null=True, upload_to='Classes')),
                ('level', models.CharField(choices=[('nd1', 'ND1'), ('nd2', 'ND2'), ('hnd1_ncc', 'HND1 NCC'), ('hnd1_swd', 'HND1 SWD'), ('hnd2_ncc', 'HND2 NCC'), ('hnd2_swd', 'HND2 SWD')], default='nd1', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50, verbose_name='Course Code')),
                ('course_title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Course Title')),
                ('credit_load', models.CharField(blank=True, max_length=20, null=True)),
                ('semester', models.CharField(choices=[('First Semester', 'First Semester'), ('Second Semester', 'Second Semester')], max_length=200)),
            ],
            options={
                'ordering': ['semester', '-level'],
            },
        ),
        migrations.CreateModel(
            name='Excos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('year', models.IntegerField(choices=base.models.get_year_choices, default=2025)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='Excos')),
            ],
            options={
                'verbose_name_plural': 'Excos',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.IntegerField(choices=base.models.get_year_choices)),
                ('ended', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'HOD',
                'verbose_name_plural': 'HODs',
                'ordering': ['-started'],
            },
        ),
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='home/')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs')),
            ],
            options={
                'verbose_name': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Labs')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=400)),
                ('regno', models.CharField(max_length=50, verbose_name='Registration Number')),
                ('designation', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('image', models.ImageField(upload_to='Team')),
            ],
            options={
                'verbose_name': 'Project Team',
                'verbose_name_plural': 'Project Teams',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('First Semester', 'First Semester'), ('Second Semester', 'Second Semester')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('qualifications', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=500, null=True)),
                ('citation', models.TextField(blank=True, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Lecturers')),
                ('is_teaching', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Staff List',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['day_of_week', 'start_time', 'level'],
            },
        ),
    ]
