# Generated by Django 5.1.7 on 2025-04-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslide',
            name='image',
            field=models.ImageField(upload_to='home/'),
        ),
    ]
