# Generated by Django 5.1.7 on 2025-06-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_blog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('qualification', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Full Time', 'Full Time'), ('Per Time', 'Per Time')], max_length=500)),
                ('citation', models.TextField(blank=True, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
