# Generated by Django 5.1.7 on 2025-06-22 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_lecturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='qualification',
            new_name='qualifications',
        ),
    ]
