# Generated by Django 5.1.7 on 2025-06-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_qualification_lecturer_qualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
