# Generated by Django 5.1.7 on 2025-06-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_lecturer_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='image',
            field=models.ImageField(upload_to='Lecturers'),
        ),
    ]
