# Generated by Django 5.1.7 on 2025-07-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_labs_alter_lecturer_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labs',
            new_name='Lab',
        ),
        migrations.AlterModelOptions(
            name='lab',
            options={'verbose_name': 'Labs'},
        ),
    ]
