# Generated by Django 5.1.7 on 2025-07-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='status',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=500),
        ),
    ]
