# Generated by Django 5.1.7 on 2025-07-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_lecturer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='is_teaching',
            field=models.BooleanField(default=True),
        ),
    ]
