# Generated by Django 5.1.7 on 2025-07-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_lecturer_is_teaching'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lecturer',
            new_name='Staff',
        ),
    ]
