# Generated by Django 5.1.7 on 2025-07-18 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_staff_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='lab',
            options={},
        ),
    ]
