# Generated by Django 5.1.7 on 2025-07-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_class_options_alter_lab_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['status', 'full_name'], 'verbose_name_plural': 'Staff List'},
        ),
    ]
