# Generated by Django 5.1.7 on 2025-07-18 22:48

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='excos',
            name='year',
            field=models.IntegerField(choices=base.models.get_year_choices, default=2025),
        ),
    ]
