# Generated by Django 5.1.7 on 2025-07-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_rename_hall_class_timetable_alter_excos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class_timetable',
            options={'verbose_name': 'Class Timetable'},
        ),
    ]
