# Generated by Django 5.1.7 on 2025-07-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_class_timetable_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='timetable',
            field=models.ImageField(default=None, upload_to='Classes'),
            preserve_default=False,
        ),
    ]
