# Generated by Django 5.1.7 on 2025-07-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_class_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Classes'),
        ),
        migrations.AlterField(
            model_name='class',
            name='timetable',
            field=models.ImageField(blank=True, null=True, upload_to='Classes'),
        ),
    ]
