# Generated by Django 5.1.7 on 2025-07-31 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_class_image_alter_class_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cs_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pnone Number')),
            ],
        ),
    ]
