# Generated by Django 5.1.7 on 2025-07-31 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_cs_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cs_Contact',
        ),
    ]
