# Generated by Django 5.1.7 on 2025-08-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_delete_cs_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Classes', verbose_name='Class Image'),
        ),
    ]
