# Generated by Django 5.1.7 on 2025-08-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_class_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class_Timetable',
        ),
    ]
