# Generated by Django 5.1.7 on 2025-08-04 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_staff_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50, verbose_name='Course Code')),
                ('course_title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Course Title')),
                ('credit_load', models.CharField(blank=True, max_length=20, null=True)),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Lecturer')),
            ],
        ),
    ]
