# Generated by Django 5.1.7 on 2025-08-04 17:21

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_course_lecturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.CharField(choices=base.models.get_year_choices, max_length=20)),
                ('ended', models.CharField(max_length=20)),
                ('lecturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.staff')),
            ],
            options={
                'ordering': ['-started'],
            },
        ),
    ]
