# Generated by Django 5.1.7 on 2025-08-04 17:29

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_hod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hod',
            options={'ordering': ['-started'], 'verbose_name': 'HOD', 'verbose_name_plural': 'HODs'},
        ),
        migrations.AlterField(
            model_name='hod',
            name='started',
            field=models.IntegerField(choices=base.models.get_year_choices, max_length=20),
        ),
    ]
