# Generated by Django 5.1.7 on 2025-08-06 17:29

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_hod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=400)),
                ('regno', models.CharField(max_length=50, verbose_name='Registration Number')),
                ('designation', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('image', models.ImageField(upload_to='Team')),
            ],
        ),
        migrations.AlterModelOptions(
            name='hod',
            options={'ordering': ['-started'], 'verbose_name': 'HOD', 'verbose_name_plural': 'HODs'},
        ),
        migrations.AlterField(
            model_name='hod',
            name='started',
            field=models.IntegerField(choices=base.models.get_year_choices),
        ),
    ]
