# Generated by Django 5.1.7 on 2025-08-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_project_team_alter_hod_options_alter_hod_started'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project_team',
            options={'verbose_name': 'Project Team', 'verbose_name_plural': 'Project Teams'},
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('First Semester', 'First Semester'), ('Second Semester', 'Second Semester')], default=None, max_length=200),
            preserve_default=False,
        ),
    ]
