# Generated by Django 5.1.7 on 2025-09-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_course_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['level']},
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('ND1', 'ND1'), ('ND2', 'ND2'), ('HND1 NCC', 'HND1 NCC'), ('HND1 SWD', 'HND1 SWD'), ('HND2 NCC', 'HND2 NCC'), ('HND2 SWD', 'HND2 SWD')], max_length=20),
        ),
    ]
