# Generated by Django 5.1.7 on 2025-09-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_alter_course_options_alter_course_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['level', 'semester']},
        ),
    ]
