# Generated by Django 5.1.7 on 2025-09-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_course_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('nd1', 'ND1'), ('nd2', 'ND2'), ('hnd1 ncc', 'HND1 NCC'), ('hnd1 swd', 'HND1 SWD'), ('hnd2 ncc', 'HND2 NCC'), ('hnd2 swd', 'HND2 SWD')], default='nd1', max_length=10)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time', 'level'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['semester', '-level']},
        ),
    ]
