# Generated by Django 5.1.7 on 2025-09-15 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_timetable_alter_course_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.course'),
        ),
    ]
