# Generated by Django 5.1.7 on 2025-09-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_class_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('nd1', 'ND1'), ('nd2', 'ND2'), ('hnd1 ncc', 'HND1 NCC'), ('hnd1 swd', 'HND1 SWD'), ('hnd2 ncc', 'HND2 NCC'), ('hnd2 swd', 'HND2 SWD')], max_length=200)),
            ],
        ),
    ]
