# Generated by Django 5.1.7 on 2025-09-17 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['-level']},
        ),
        migrations.AlterField(
            model_name='timetable',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_level', to='base.level'),
        ),
    ]
