# Generated by Django 5.1.7 on 2025-09-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_alter_level_options_alter_timetable_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='level',
            field=models.CharField(choices=[('nd1', 'ND1'), ('nd2', 'ND2'), ('hnd1 ncc', 'HND1 NCC'), ('hnd1 swd', 'HND1 SWD'), ('hnd2 ncc', 'HND2 NCC'), ('hnd2 swd', 'HND2 SWD')], default='nd1', max_length=10),
        ),
    ]
