# Generated by Django 5.1.7 on 2025-09-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_alter_timetable_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.CharField(choices=[('nd1', 'ND1'), ('nd2', 'ND2'), ('hnd1_ncc', 'HND1 NCC'), ('hnd1_swd', 'HND1 SWD'), ('hnd2_ncc', 'HND2 NCC'), ('hnd2_swd', 'HND2 SWD')], default='nd1', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('ND1', 'ND1'), ('ND2', 'ND2'), ('HND1_NCC', 'HND1 NCC'), ('HND1_SWD', 'HND1 SWD'), ('HND2_NCC', 'HND2 NCC'), ('HND2_SWD', 'HND2 SWD')], default='ND1', max_length=20),
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(choices=[('nd1', 'ND1'), ('nd2', 'ND2'), ('hnd1_ncc', 'HND1 NCC'), ('hnd1_swd', 'HND1 SWD'), ('hnd2_ncc', 'HND2 NCC'), ('hnd2_swd', 'HND2 SWD')], max_length=200),
        ),
    ]
