# Generated by Django 5.1.7 on 2025-10-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_alter_class_level_alter_course_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={},
        ),
        migrations.AddField(
            model_name='excos',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
